# nginx-svc-np.yaml
apiVersion: v1
kind: Service 
metadata:
  name: explorer-app
  labels:
    app: explorer-app
spec:
  selector:
    app: explorer-app
  type: NodePort
  ports:
    - nodePort: 31111
      port: 8080
      targetPort: 8080
