apiVersion: v1
kind: PersistentVolume
metadata:
  name: explorer-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  hostPath:
    path: "/home/sunnysingh97g/go/src/github.com/sunnysingh97/hypexp/explorer-data"
